name: .NET

on:
  push:
    branches: [ main ]
    tags:
     - '*'

  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: true
    - name: Set Build Infos
      run: |
          ./update_build_infos.ps1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish /p:PublishProfile=Portable -c Release -o output
    - shell: pwsh
      env:
        MINISIGN_KEY: ${{ secrets.MINISIGN_KEY }}
      run: |
        .\sign_file.ps1 .\output\jxlgui.wpf.exe
    - name: Compress Publish
      run: Compress-Archive -Path .\output\jxlgui.wpf.exe* .\output\jxlgui.wpf.exe.zip    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: output\jxlgui.wpf.exe.zip
