name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Set Build Infos
      run: |
          ./update_build_infos.ps1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o output
    - name: minisign-cli
      uses: thomasdesr/minisign-action@v1.1
      with:
        args: -Sm .\output\jxlgui.wpf.exe
        minisign_key: ${{ secrets.SuperSecret }}
    - name: Compress Publish
      run: Compress-Archive -Path .\output\jxlgui.wpf.exe* .\output\jxlgui.wpf.exe.zip    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: output\jxlgui.wpf.exe.zip
